import json
from pathlib import Path

COMPONENTS_PATH = Path("server", "components")
REQUIREMENT_PATH = Path("requirements-components.txt")

with open(REQUIREMENT_PATH, "w") as f:
    f.write("# This file is automatically generated. Do not edit.\n")

    components = sorted(
        [component for component in COMPONENTS_PATH.iterdir() if component.is_dir()],
        key=lambda x: x.name,
    )

    for component in components:
        manifest_path = component / "manifest.json"

        if not manifest_path.exists():
            continue

        manifest_file = json.load(open(manifest_path))
        requirements = manifest_file.get("requirements", {})

        if not requirements:
            continue

        f.write(f"\n# {component.name}\n")
        for package, version in requirements.items():
            f.write(f"{package}=={version}\n")
